# Generated by Django 3.0.4 on 2020-03-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='url',
            field=models.URLField(default=False),
        ),
    ]
